<?php
$plano = $plano ?? null;
$isEdit = $plano !== null;
$enabled = array_flip($enabledModules ?? []);
?>
<div class="container-fluid py-4 saas-admin">
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><h1 class="h3 mb-1"><?= htmlspecialchars($title) ?></h1><p class="text-muted mb-0">Configure preço, capacidade e recursos liberados por assinatura.</p></div><a href="/painel/planos" class="btn btn-light"><i class="fas fa-arrow-left me-1"></i> Voltar</a></div>
    <?php if (!empty($_GET['error'])): ?><div class="alert alert-danger"><?= htmlspecialchars((string) $_GET['error']) ?></div><?php endif; ?>
    <form method="post" action="<?= $isEdit ? '/painel/planos/update/' . (int) $plano->id : '/painel/planos' ?>" class="card border-0 shadow-sm"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'] ?? '') ?>"><div class="card-body p-4"><div class="row g-3 mb-4"><div class="col-md-4"><label class="form-label">Nome *</label><input class="form-control" name="nome" required value="<?= htmlspecialchars($plano->nome ?? '') ?>"></div><div class="col-md-3"><label class="form-label">Slug *</label><input class="form-control" name="slug" required pattern="[a-z0-9-]{3,60}" value="<?= htmlspecialchars($plano->slug ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Ordem</label><input class="form-control" type="number" min="0" name="ordem" value="<?= (int) ($plano->ordem ?? 0) ?>"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="ativo" <?= (($plano->status ?? 'ativo') === 'ativo') ? 'selected' : '' ?>>Ativo</option><option value="inativo" <?= (($plano->status ?? '') === 'inativo') ? 'selected' : '' ?>>Inativo</option></select></div><div class="col-md-6"><label class="form-label">Preço mensal (R$)</label><input class="form-control" inputmode="decimal" name="preco_mensal" value="<?= htmlspecialchars((string) ($plano->preco_mensal ?? '0.00')) ?>"></div><div class="col-md-6"><label class="form-label">Limite de usuários</label><input class="form-control" type="number" min="1" name="limite_usuarios" value="<?= $plano && $plano->limite_usuarios !== null ? (int) $plano->limite_usuarios : '' ?>" placeholder="Em branco = ilimitado"></div><div class="col-12"><label class="form-label">Descrição</label><textarea class="form-control" name="descricao" rows="2"><?= htmlspecialchars($plano->descricao ?? '') ?></textarea></div></div>
        <h2 class="h5 border-top pt-4">Módulos liberados</h2><p class="text-muted small">Além do papel do usuário, o plano precisa liberar o módulo para que ele apareça e seja acessível.</p><div class="row g-2">
        <?php foreach ($availableModules as $slug => $label): ?><div class="col-md-6 col-xl-4"><label class="border rounded p-3 d-flex align-items-center gap-2 w-100 h-100"><input class="form-check-input mt-0" type="checkbox" name="modules[]" value="<?= htmlspecialchars($slug) ?>" <?= isset($enabled[$slug]) ? 'checked' : '' ?>><span><strong><?= htmlspecialchars($label) ?></strong><br><small class="text-muted"><?= htmlspecialchars($slug) ?></small></span></label></div><?php endforeach; ?>
        </div></div><div class="card-footer bg-white d-flex justify-content-between"><a href="/painel/planos" class="btn btn-light">Cancelar</a><button class="btn btn-primary" type="submit"><i class="fas fa-save me-1"></i> Salvar Plano</button></div></form>
</div>
